name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: bun
        run: bun install
        working-directory: ./
      - name: tsc
        run: bun run lint:ts
        working-directory: ./
      - name: Run Biome
        run: biome ci .
      - name: Lint
        run: bun run lint
        working-directory: ./
      - name: Test
        run: bun run test
        working-directory: ./
